language: scala

cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sbt"
  - "$HOME/.ivy2"

scala:
- 2.11.6

jdk:
- oraclejdk9

script:
- sbt clean coverage test package
# Trick to avoid unnecessary cache updates
- find $HOME/.sbt -name "*.lock" | xargs rm

# notifications:
#   email:
#   - S24-PlatformEngineering-CPE-Horus@scout24.com 
#   slack:
#     rooms:
#       - 
#     on_success: change
#     on_failure: always

after_success:
  - >
      sbt coveralls &&
      sh "$TRAVIS_BUILD_DIR/travis-ci-bintray-credentials.sh" &&
      sbt publish
